services:

  postgres:
    image: postgres:16.4-alpine
    container_name: postgres_container
    hostname: ${POSTGRES_HOST}
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data       
      - ./db_init_scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 120s
      timeout: 5s
      retries: 3
  
  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin_container
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_PORT=${PGADMIN_PORT}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    volumes:
      - ./pgadmin-init.sh:/entrypoint_custom.sh
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    user: root
    entrypoint: /entrypoint_custom.sh
    ports:
      - $PGADMIN_PORT:80
    networks:
      - app_network
  
  php_api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: php_container
    env_file: .env
    volumes:
      - ./api:/var/www/html
    ports:
      - ${PHP_API_PORT}:80
    networks:
      - app_network
    depends_on:
      - postgres

  web-app:
    build:
      context: web-app
      dockerfile: Dockerfile
      args:
        PORT: ${REACT_APP_PORT}
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
    image: react_app_image
    container_name: react_container
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./web-app:/app
      - /app/node_modules
    depends_on:
      - postgres
      - php_api
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data:
