services:

  postgres:
    image: postgres:16.4-alpine
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin_container
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    ports:
      - $PGADMIN_PORT:80
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  pg_data:
  pgadmin_data:
